public static final String ANSI_RESET = "\u001B[0m"; 
public static final String ANSI_BLACK = "\u001B[30m";
public static final String ANSI_RED = "\u001B[31m";  //3
public static final String ANSI_GREEN = "\u001B[32m";  //5
public static final String ANSI_YELLOW = "\u001B[33m";  //6
public static final String ANSI_BLUE = "\u001B[34m";  //4
public static final String ANSI_PURPLE = "\u001B[35m"; //1
public static final String ANSI_CYAN = "\u001B[36m";    //2
public static final String ANSI_WHITE = "\u001B[37m";
public static final String ANSI_BLACKBACKGROUND = "\u001B[37;40m";  //7
